export const darkTheme = {
  main: "#1F2128",
  secondary: "#191b1f",
  color: " #FFFFFF",
  componentBackground: "#2C2F36",
  themeIcon: "https://i.ibb.co/KKSzz6f/Iconly-Bulk-Scan.png",
  searchIcon: "https://i.ibb.co/fnvTZNt/search-icon.png",
  exchangeIcon: "https://i.ibb.co/gz4ykGS/Icon-awesome-exchange-alt.png",
  stackIcon: "https://i.ibb.co/vz0fLdP/Icon-awesome-layer-group.png",
  linkIcon: "https://i.ibb.co/z8Jb255/Icon-awesome-link.png",
  cellBorderColor: "#707070",
  red: "#fe1040",
  green: "#00fc2a",
  bar: "#171924",
  progress: "#323546",
  barBorder: "#1f2128",
  barTextLeft: "#b4b9d4",
  barTextRight: "#82869e",
  secondaryText: "#adaaa8",
  blue: "#007ea7",
};
export const lightTheme = {
  main: "#f7f7f7",
  secondary: "#fff",
  color: "#2C2F36",
  componentBackground: "#edeff2",
  themeIcon: "https://i.ibb.co/9v0sHFQ/theme-icon-dark.png",
  searchIcon: "https://i.ibb.co/CMm54Wz/search-icon-dark.png",
  exchangeIcon: "https://i.ibb.co/cXvZ9NL/Icon-awesome-exchange-alt.png",
  stackIcon: "https://i.ibb.co/NWh5gVd/Icon-awesome-layer-group.png",
  linkIcon: "https://i.ibb.co/5LVKqPc/Icon-awesome-link.png",
  cellBorderColor: "#DCDCDC",
  red: "#fe1040",
  green: "#00fc2a",
  bar: "#eff2f5",
  progress: "#cfd6e4",
  barBorder: "white",
  barTextLeft: "#82869e",
  barTextRight: "#b4b9d4",
  secondaryText: "#adaaa8",
  blue: "#007ea7",
};
